//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwidnikHackaton.DB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurements
    {
        public int ID { get; set; }
        public int StreetID { get; set; }
        public int CurrentSpeed { get; set; }
        public int FreeFlowSpeed { get; set; }
        public int CurrentTravelTime { get; set; }
        public int FreeFlowTravelTime { get; set; }
        public System.DateTime MeasureDate { get; set; }
    
        public virtual Streets Streets { get; set; }
    }
}
