//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwidnikHackaton.DB2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Swidnik2Entities : DbContext
    {
        public Swidnik2Entities()
            : base("name=Swidnik2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coordinates> Coordinates { get; set; }
        public virtual DbSet<Measurements> Measurements { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
    }
}
